application: hub-ology
version: dev
runtime: python
api_version: 1



handlers:
- url: /static
  static_dir: hubology/static
- url: /favicon.ico
  static_files: hubology/static/favicon.ico
  upload: hubology/static/favicon.ico
- url: .*
  script: main.py
